# Generated by Django 4.0.5 on 2022-07-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contact_mobile_alter_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='add_info',
            new_name='addinfo',
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
