# Generated by Django 4.0.5 on 2022-07-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_user_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_name', models.CharField(max_length=100)),
                ('sneaker_size', models.CharField(max_length=10)),
                ('sneaker_price', models.PositiveIntegerField()),
                ('sneaker_desc', models.TextField()),
                ('sneaker_image', models.ImageField(upload_to='sneaker_image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
