# Generated by Django 4.0.5 on 2022-07-28 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_price',
            new_name='sneaker_price',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_qty',
            new_name='sneaker_qty',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
    ]
