# Generated by Django 4.0.5 on 2022-07-28 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_product_price_cart_sneaker_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
