# Generated by Django 4.0.5 on 2022-08-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sneaker_price',
            new_name='net_price',
        ),
    ]
